version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Kyiv
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      rust-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
    assignees:
      - dmytro-yemelianov
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Kyiv
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    assignees:
      - dmytro-yemelianov
    commit-message:
      prefix: ci
      include: scope
